version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: todolist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: todolist_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
